### ISSUE TITLE
您好请教下，我这个qqlt+华硕z170可以直接使用吗？现在是11.6.4，用这个可以吗？还是说一定要蒙特雷

### ISSUE THREAD

**Issue by Lululu-0715** [yebuwudong/EFI-z170-qqls#1]
您好请教下，我这个qqlt+华硕z170可以直接使用吗？现在是11.6.4，用这个可以吗？还是说一定要蒙特雷

**Comment by yebuwudong** [comment]
可以使用---- 回复的原邮件 ***@***.***>发送日期2022年03月14日 15:41 ***@***.***> ***@***.***>主题[yebuwudong/EFI-z170-qqls] 您好请教下，我这个qqlt+华硕z170可以直接使用吗？现在是11.6.4，用这个可以吗？还是说一定要蒙特雷 (Issue #1)

您好请教下，我这个qqlt+华硕z170可以直接使用吗？现在是11.6.4，用这个可以吗？还是说一定要蒙特雷



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/yebuwudong/EFI-z170-qqls/issues/1",

"url": "https://github.com/yebuwudong/EFI-z170-qqls/issues/1",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by yebuwudong** [comment]
下载最新0.7.9版本

**Comment by Lululu-0715** [comment]
谢谢，我可以直接替换本来的efi不用升级系统到蒙特雷是吧，之前自己弄了个efi有很多问题，所以就来抄作业了。哈哈

**Comment by yebuwudong** [comment]
替换efi记得清理nvram，bios设置也要注意

**Comment by Lululu-0715** [comment]
收nvram？

**Comment by yebuwudong** [comment]
引导界面按空格键，选择nvram选项

**Comment by Lululu-0715** [comment]
这个知道清空那啥，多谢

**Comment by Lululu-0715** [comment]
是清空好换还是替换后清空


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yebuwudong/EFI-z170-qqls"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yebuwudong/EFI-z170-qqls] 您好请教下，我这个qqlt+华硕z170可以直接使用吗？现在是11.6.4，用这个可以吗？还是说一定要蒙特雷 (Issue #1)





 
引导界面按空格键，选择nvram选项
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yebuwudong** [comment]
换好再清理
